name: Code Review

on:
  pull_request:
    branches:
      - main2

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Linters
      run: npm run lint
    - name: Code Quality Analysis
      run: npm run quality-check
