name: Custom Workflow

on:
  release:
    types: [created]

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Release Notes
      uses: github-tools/github-release-notes@main


      with:
        token: ${{ secrets.TOKEN_GITHUB }}
        tag_name: ${{ github.ref }}
