name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for updates
      run: npm update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update dependencies
        title: '[AUTO] Update dependencies'
        body: 'Automatically update project dependencies'
