name: Deployment Pipeline

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Make sure this version matches the one you want to use based on your package.json
    - name: Install dependencies
      run: npm install
    # Removed the "Build" step since you mentioned a Docker build, which typically includes compilation.
    - name: Test
      run: npm test
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-region: us-east-1
    - name: Build and Push Docker image
      run: |
        docker build -t yourawsaccountid.dkr.ecr.us-east-1.amazonaws.com/your-image-name .
        docker push yourawsaccountid.dkr.ecr.us-east-1.amazonaws.com/your-image-name
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
